[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://images.unsplash.com/.*",
    "https://icon.icepanel.io/.*"
  ]
